version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
       - checkout
       - run: cd source/JenkinsToRazer
       - run: ./gradlew_win linkReleaseExecutableWindows
       - run:
           command: |
               cd source/JenkinsToRazer
               ./gradlew_win linkReleaseExecutableWindows
