version: 2.1
jobs:
  build_windows_release_executable:
    machine:
      image: ubuntu-1604:201903-01
    steps:
       - checkout
       - run:
           name: "Build Windows release artifact"
           command: |
               cd source/JenkinsToRazer
               ./gradlew_win linkReleaseExecutableWindows
               cp -r build/bin/windows/releaseExecutable/ /tmp/releaseArtifacts
       - store_artifacts:
           path: /tmp/releaseArtifacts
       - persist_to_workspace:
           root: /tmp
           paths:
             - releaseArtifacts

  publish_github_release_draft:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Publish Release Draft on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${VERSION} -draft ${VERSION} /tmp/releaseArtifacts

workflows:
  version: 2
  build_release_artifacts_and_publish_release_draft:
    jobs:
      - build_windows_release_executable: &build_release_artifacts_and_publish_release_draft_filter
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish_github_release_draft:
          requires:
            - build_windows_release_executable
          <<: *build_release_artifacts_and_publish_release_draft_filter
