name: JenkinsToRazer CI Build

on:
  push:
    branches:
      - develop
 
jobs:
  windows-ci-build:
    name: Windows CI Build
    runs-on: windows-latest
    steps:

    - name: Setup MSYS2 Environment
      run: |
        choco install msys2
        refreshenv
        pacman -S --noconfirm mingw-w64-x86_64-curl
      shell: cmd  

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Debug Executable
      run: |
        cd source/JenkinsToRazer/
        gradlew linkDebugExecutableWindows
        cd ../..
      shell: cmd  

    - name: Store artifact
      uses: actions/upload-artifact@v1
      with:
        name: DebugExecutable
        path: .source/JenkinsToRazer/build/bin/windows/debugExecutable/